name: Build K3

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false 
        default: 'false'
    
env:
  images_dir: ~/images
  ET0MACADDR: "98:BB:99:2F:4B:37"    
  MACADDR1_24G: "98:BB:99:2F:4B:38"
  MACADDR2_5G: "98:BB:99:2F:4B:39"

jobs:
  build:
    runs-on: Ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
       sudo dpkg --add-architecture i386
       sudo dpkg-reconfigure dash
       sudo apt-get install libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf automake bash bison \
       bzip2 diffutils file flex m4 g++ gawk groff-base libncurses5-dev libtool libslang2 make patch perl pkg-config shtool \
       subversion tar texinfo zlib1g zlib1g-dev git gettext libexpat1-dev libssl-dev cvs gperf unzip \
       python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-multilib libncurses5 mtd-utils \
       libncurses5-dev libvorbis-dev git autopoint autogen automake-1.15 sed build-essential intltool libglib2.0-dev \
       xutils-dev lib32z1-dev lib32stdc++6 xsltproc gtk-doc-tools gitk libelf1:i386
       
       reboot

    - name: Clone source code
      run: | 
        cd $HOME
        git clone https://github.com/dawenhaozx/asuswrt-merlin.ng
        git clone https://github.com/ghostnup/k3screenctrl asuswrt-merlin.ng/release/src/router/k3screenctrl 
        git clone https://github.com/RMerl/am-toolchains.git
        mkdir amng-build
        rsync -a --del asuswrt-merlin.ng/ amng-build
        mkdir -p images
      
    - name: Link Directory
      run: |       
        sudo ln -s ~/am-toolchains/brcm-arm-hnd /opt/toolchains
        echo "export LD_LIBRARY_PATH=\$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.profile
        echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        sudo ln -s ~/am-toolchains/brcm-arm-hnd /opt/toolchains
        echo "export LD_LIBRARY_PATH=\$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ~/.profile
        echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
        sudo ln -s ~/amng-build/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm
        ln -s ~/amng-build/am-toolchains/brcm-arm-sdk  ~/amng-build/release/src-rt-6.x.4708/toolchains
        echo "PATH=\$PATH:/opt/brcm-arm/bin" >> ~/.profile
        sudo ln -sf bash /bin/sh
        
       
    - name: Modify File
      run: |        
        cd  ~/amng-build/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed
        sed -i 's/^\(et0macaddr=\).*/\1${{ env.ET0MACADDR }}/g' rt-k3_nvram.txt
        sed -i 's/^\(0:macaddr=\).*/\1${{ env.MACADDR1_24G }}/g' rt-k3_nvram.txt
        sed -i 's/^\(1:macaddr=\).*/\1${{ env.MACADDR2_5G }}/g' rt-k3_nvram.txt
        
    - name: Build Firmware
      run: |
      
        cd ~/amng-build/release/src-rt-7.14.114.x/src
        make rt-k3
        echo "build image done"     
        
        cd ~/amng-build/release/src-rt-7.14.114.x/src/cfe
        make
        echo "build cfe done"
        
    - name: Move file
      run: |
        sudo mv -f ~/amng-build/release/src-rt-7.14.114.x/src/image/*.trx ~/images
        cp ~/amng-build/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed/rt-k3_nvram.txt ~/images
        cp ~/amng-build/release/src-rt-7.14.114.x/src/cfe/cfe*.bin ~/images

    - name: Upload images to Artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2.2.1
      with:
          name: k3ml
          path: ${{ env.images_dir }}
          
#     - name: Upload images to Artifact2
#       if: ${{ success() }}
#       uses: actions/upload-artifact@v2.2.1
#       with:
#           name: k3ml2
#           path: ${{ env.images_dir }}
